name: Publish Docs
on:
  push:
    branches: [main]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Instalar DocFX
        run: dotnet tool install -g docfx
      - name: Generar metadata
        run: docfx metadata docfx.json
      - name: Generar sitio
        run: docfx build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site