name: Snyk Analysis
env:
  DOTNET_VERSION: '8.x'
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: snyk/actions/setup@master
      - name: Configurando la versión de NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Instalar snyk-to-html
        run: npm install -g snyk-to-html
      - name: Snyk test (dependencias)
        run: snyk test --json | snyk-to-html -o dependencies-test-results.html
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Subir artefacto HTML
        uses: actions/upload-artifact@v4
        with:
          name: snyk-html-report
          path: dependencies-test-results.html